PagedGeometry: Forests::GrassPage Class Reference
Forests::GrassPage Class Reference
A custom page type designed specifically for use with GrassLoader.
#include <GrassLoader.h>
Public Member Functions
void init (PagedGeometry *geom, const Ogre::Any &data)
Prepare a geometry page for use.
void addEntity (Ogre::Entity *ent, const Ogre::Vector3 &position, const Ogre::Quaternion &rotation, const Ogre::Vector3 &scale, const Ogre::ColourValue &color)
Add an entity to the page, at the specified position, rotation, and scale.
void removeEntities ()
Remove all geometry/entities from the page completely.
void setFade (bool enabled, Ogre::Real visibleDist, Ogre::Real invisibleDist)
Sets fade behavior for this page.
void setVisible (bool visible)
Toggle the entire page's visibility.
Public Member Functions inherited from Forests::GeometryPage
void setQueryFlag (Ogre::uint32 flag)
bool hasQueryFlag ()
Ogre::uint32 getQueryFlag ()
virtual void setRegion (Ogre::Real left, Ogre::Real top, Ogre::Real right, Ogre::Real bottom)
Prepare a geometry page for entities.
virtual void build ()
Perform any final steps to make added entities appear in the scene.
virtual void update ()
Do whatever needs to be done to keep the page geometry up-to-date.
Ogre::Vector3 & getCenterPoint ()
Gets the center point of the page.
bool isVisible ()
Return the current visibility status of the page.
virtual const Ogre::AxisAlignedBox & getBoundingBox ()
Advanced: Return the bounding box computed with addEntityToBoundingBox()
virtual void addEntityToBoundingBox (Ogre::Entity *ent, const Ogre::Vector3 &position, const Ogre::Quaternion &rotation, const Ogre::Vector3 &scale)
Advanced: Expand the current bounding box to include the given entity.
virtual void clearBoundingBox ()
Advanced: Reset the bounding box used by addEntityToBoundingBox()
virtual ~GeometryPage ()
Destructor This is defined here so the destructors of derived classes are called properly.
GeometryPage ()
Constructor Initialise everything to zero, false or NULL except for _trueBoundsUndefined that is set to true.
Detailed Description
A custom page type designed specifically for use with GrassLoader.
You can use this in your own project if you want, but remember that no optimizations are performed. The given entity is simply cloned and attached to a new scene node as quickly and simply as possible (this means there's no batching overhead as in BatchPage, but it also means potentially poor performance if you don't know what you're doing).
Member Function Documentation
init()
void Forests::GrassPage::init (PagedGeometry * geom, const Ogre::Any & data) virtual
Prepare a geometry page for use.
Parameters
geom The PagedGeometry object that's creating this GeometryPage.
data A single parameter of custom data (optional).
This is called immediately after creating a new GeometryPage. It is never called more than once for a single instance of your geometry page.
The "data" parameter is set for all pages when PagedGeometry::addDetailLevel() is called. This parameter is optional and can be used for whatever you like if you need a constructor parameter of some kind. Be sure to document what kind of variable the user needs to supply and what it's purpose is in your GeometryPage implementation.
Note
If you need to get the current camera, scene manager, etc., use the geom parameter. The PagedGeometry class contains inline methods you can use to access the camera and scene manager.
Warning
Do NOT store a local copy of geom->getCamera()! The camera returned by this function may change at any time!
Implements Forests::GeometryPage.
References Forests::PagedGeometry::getSceneManager(), and Forests::PagedGeometry::getSceneNode().
addEntity()
void Forests::GrassPage::addEntity (Ogre::Entity * ent, const Ogre::Vector3 & position, const Ogre::Quaternion & rotation, const Ogre::Vector3 & scale, const Ogre::ColourValue & color) virtual
Add an entity to the page, at the specified position, rotation, and scale.
Parameters
ent The entity that is being added. Keep in mind that the same entity may be added multiple times.
position The position where the entity must be placed. Under normal circumstances, this will never be outside of the bounds supplied to init(). The only exception is when a PageLoader tries to add an entity outside of the bounds it was given.
rotation The rotation which should be applied to the entity.
scale The scale which should be applied to the entity.
color The desired color to apply to the whole entity
Note
The entity does not have to actually appear in the scene until build() is called.
Implements Forests::GeometryPage.
References Ogre::SceneNode::attachObject(), Ogre::SceneNode::createChildSceneNode(), Ogre::MovableObject::getRenderQueueGroup(), Ogre::MovableObject::setCastShadows(), Ogre::Node::setPosition(), Ogre::MovableObject::setQueryFlags(), and Ogre::Entity::setRenderQueueGroup().
removeEntities()
void Forests::GrassPage::removeEntities () virtual
Remove all geometry/entities from the page completely.
Make sure this completely reverses the effects of both build() and addEntity(). This is necessary, because after this is called, the entities will most likely be added again with addEntity() and build().
Do not leave any remains of the entities in memory after this function is called. One of the advantages of using paged geometry is that you can have near-infinite game worlds, which would normally exceed a computer's RAM capacity. This advantage would completely disappear if you did not clean up properly when the page manager calls this function.
Implements Forests::GeometryPage.
References Ogre::SceneNode::getAttachedObject(), Ogre::Entity::getMesh(), Ogre::Resource::getName(), Ogre::MeshManager::getSingleton(), Ogre::SceneNode::numAttachedObjects(), and Ogre::ResourceManager::remove().
setFade()
void Forests::GrassPage::setFade (bool enabled, Ogre::Real visibleDist, Ogre::Real invisibleDist) inline virtual
Sets fade behavior for this page.
Parameters
enabled Whether or not to enable fading
visibleDist The distance where geometry will be fully opaque (alpha 1)
invisibleDist The distance where geometry will be invisible (alpha 0)
This is called whenever a page needs fading enabled/disabled. The distance ranges given specify how the final alpha values should be calculated - geometry at visibleDist should have alpha values of 1, while geometry at invisibleDist should have alpha values of 0. Important: Distances must be calculated in the xz plane only - the y coordinate should be disregarded when calculating distance.
setFade() won't be called unless the user's computer supports vertex shaders.
Note
invisibleDist may be greater than or less than visibleDist, depending on whether the geometry is fading out or in to the distance.
Implements Forests::GeometryPage.
setVisible()
void Forests::GrassPage::setVisible (bool visible) virtual
Toggle the entire page's visibility.
Parameters
visible Whether or not this page should be visible.
Implements Forests::GeometryPage.
References Ogre::SceneNode::setVisible().