PagedGeometry: Forests::BatchedGeometry Class Reference
Forests::BatchedGeometry Class Reference
A "lightweight" version of Ogre::StaticGeometry, which gives you a little more control over the batch materials, etc.
#include <BatchedGeometry.h>
Classes
class SubBatch
Visible chunk of geometry.
Public Types
typedef std::map< Ogre::String, SubBatch * > TSubBatchMap
Stores a list of GeomBatch'es, using a format string (generated with getGeometryFormatString()) as the key value.
typedef Ogre::MapIterator< TSubBatchMap > TSubBatchIterator
typedef Ogre::ConstMapIterator< TSubBatchMap > TConstSubBatchIterator
Public Types inherited from Ogre::ShadowCaster
typedef Ogre::ShadowRenderableList ShadowRenderableList
typedef VectorIterator< ShadowRenderableList > ShadowRenderableListIterator
Public Member Functions
BatchedGeometry (Ogre::SceneManager *mgr, Ogre::SceneNode *rootSceneNode)
Constructor.
TConstSubBatchIterator getSubBatchIterator () const
TSubBatchIterator getSubBatchIterator ()
virtual void addEntity (Ogre::Entity *ent, const Ogre::Vector3 &position, const Ogre::Quaternion &orientation=Ogre::Quaternion::IDENTITY, const Ogre::Vector3 &scale=Ogre::Vector3::UNIT_SCALE, const Ogre::ColourValue &color=Ogre::ColourValue::White)
void build ()
void clear ()
Ogre::Vector3 _convertToLocal (const Ogre::Vector3 &globalVec) const
const Ogre::AxisAlignedBox & getBoundingBox (void) const
Ogre::Real getBoundingRadius (void) const
Public Member Functions inherited from Ogre::MovableObject
MovableObject (const String &name)
MovableObjectFactory * _getCreator (void) const
LightList * _getLightList ()
SceneManager * _getManager (void) const
virtual const Affine3 & _getParentNodeFullTransform (void) const
virtual void _notifyAttached (Node *parent, bool isTagPoint=false)
virtual void _notifyCreator (MovableObjectFactory *fact)
virtual void _notifyManager (SceneManager *man)
virtual void _notifyMoved (void)
virtual void _releaseManualHardwareResources ()
virtual void _restoreManualHardwareResources ()
void addQueryFlags (uint32 flags)
void addVisibilityFlags (uint32 flags)
void detachFromParent (void)
Real getBoundingRadiusScaled () const
bool getCastShadows (void) const override
uint32 getLightMask () const
Listener * getListener (void) const
const String & getName (void) const
Node * getParentNode (void) const
SceneNode * getParentSceneNode (void) const
Real getPointExtrusionDistance (const Light *l) const override
virtual uint32 getQueryFlags (void) const
bool getReceivesShadows ()
Real getRenderingDistance (void) const
Real getRenderingMinPixelSize () const
uint8 getRenderQueueGroup (void) const
virtual uint32 getTypeFlags (void) const
const Any & getUserAny (void) const
UserObjectBindings & getUserObjectBindings ()
const UserObjectBindings & getUserObjectBindings () const
virtual uint32 getVisibilityFlags (void) const
bool getVisible (void) const
const AxisAlignedBox & getWorldBoundingBox (bool derive=false) const override
virtual const Sphere & getWorldBoundingSphere (bool derive=false) const
bool isAttached (void) const
bool isDebugDisplayEnabled (void) const
virtual bool isInScene (void) const
bool isParentTagPoint () const
const LightList & queryLights (void) const
void removeQueryFlags (uint32 flags)
void removeVisibilityFlags (uint32 flags)
void setCastShadows (bool enabled)
void setDebugDisplayEnabled (bool enabled)
void setLightMask (uint32 lightMask)
void setListener (Listener *listener)
void setQueryFlags (uint32 flags)
void setRenderingDistance (Real dist)
void setRenderingMinPixelSize (Real pixelSize)
virtual void setRenderQueueGroup (uint8 queueID)
virtual void setRenderQueueGroupAndPriority (uint8 queueID, ushort priority)
void setUserAny (const Any &anything)
void setVisibilityFlags (uint32 flags)
void setVisible (bool visible)
Public Member Functions inherited from Ogre::ShadowCaster
const AxisAlignedBox & getDarkCapBounds (const Light &light, Real dirLightExtrusionDist) const
virtual EdgeData * getEdgeList (void)
const AxisAlignedBox & getLightCapBounds (void) const
virtual const ShadowRenderableList & getShadowVolumeRenderableList (const Light *light, const HardwareIndexBufferPtr &indexBuffer, size_t &indexBufferUsedSize, float extrusionDistance, int flags=0)
bool hasEdgeList ()
Public Member Functions inherited from Ogre::AnimableObject
virtual AnimableValuePtr createAnimableValue (const String &valueName)
virtual const StringVector & getAnimableValueNames (void) const
Static Protected Member Functions
static Ogre::String getFormatString (Ogre::SubEntity *ent)
static void extractVertexDataFromShared (const Ogre::MeshPtr &mesh)
Protected Attributes
bool m_Built
bool m_BoundsUndefined
Ogre::Vector3 m_vecCenter
Ogre::AxisAlignedBox m_boundsAAB
TSubBatchMap m_mapSubBatch
Static Protected Attributes
static size_t s_vertexType2Size [Ogre::VET_UBYTE4_NORM+1] = {0}
Internal matrix for remap vertex type to vertex size instead call VertexElement::getTypeSize.
Additional Inherited Members
Static Public Member Functions inherited from Ogre::MovableObject
static uint32 getDefaultQueryFlags ()
static uint32 getDefaultVisibilityFlags ()
static void setDefaultQueryFlags (uint32 flags)
static void setDefaultVisibilityFlags (uint32 flags)
Static Public Member Functions inherited from Ogre::ShadowCaster
static void clearShadowRenderableList (ShadowRenderableList &shadowRenderables)
static void extrudeVertices (const HardwareVertexBufferSharedPtr &vertexBuffer, size_t originalVertexCount, const Vector4 &lightPos, Real extrudeDist)
Detailed Description
A "lightweight" version of Ogre::StaticGeometry, which gives you a little more control over the batch materials, etc.
Member Function Documentation
build()
void BatchedGeometry::build (void)
Make sure the batch hasn't already been built
References Ogre::SceneNode::attachObject(), Ogre::SceneNode::createChildSceneNode(), Ogre::AxisAlignedBox::getCenter(), Ogre::AxisAlignedBox::getMaximum(), Ogre::AxisAlignedBox::getMinimum(), Vector< 3, Real >::length(), OGRE_EXCEPT, Ogre::AxisAlignedBox::setMaximum(), and Ogre::AxisAlignedBox::setMinimum().
Referenced by Forests::BatchPage::build().